
export const FETCH_TOKEN='FETCH_TOKEN'
export const SEARCHING='ARTIST_SEARCHING'
export const SEARCHING_RESULT='ARTIST_SEARCHING_RESULT'
export const DISACTIVATING_SEARCH='DISACTIVATING_SEARCH'

export const FETCH_ARTISTS='FETCH_ARTISTS'
export const ARTISTS_ERROR='ARTISTS_ERROR'
export const ARTISTS_LOADING='ARTISTS_LOADING'
export const ARTISTS_SHOW='ARTISTS_SHOW'
export const SEARCH_ARTISTS='SEARCH_ARTISTS'
export const SEARCHING_RESULT_ARTIST='SEARCHING_RESULT_ARTIST'




export const FETCH_ALBUMS='FETCH_ALBUMS'
export const ALBUMS_ERROR='ALBUMS_ERROR'
export const ALBUMS_LOADING='ALBUMS_LOADING'
export const ALBUMS_SHOW='ALBUMS_SHOW'
export const SEARCH_ALBUMS='SEARCH_ALBUMS'
export const FETCH_ALBUMS_ALL='FETCH_ALBUMS_ALL'





export const FETCH_TRACKS='FETCH_TRACKS'
export const TRACKS_ERROR='TRACKS_ERROR'
export const TRACKS_LOADING='TRACKS_LOADING'
export const TRACKS_SHOW='TRACKS_SHOW'
export const SEARCH_TRACKS='SEARCH_TRACKS'
export const FETCH_TRACKS_ALL='FETCH_TRACKS_ALL'



